# ✅ render.yaml corregido para Mia Evaluación

services:
  - type: web
    name: mia-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free

  - type: web
    name: mia-frontend
    runtime: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
    plan: free
